stt:
  model: vosk
  model_name: vosk/swahili
  device: cpu
  real_time: false
  streaming: false
  vad_enabled: true
  language: sw
  cache_enabled: false
  cache_redis_url: null
  cache_ttl: 3600
  log_level: INFO
  log_file: logs/xtrad_stt.log
  max_concurrency: 1
  batch_size: 1
  model_path: null
  edge_mode: true
  vad_sensitivity: 0.3
  min_speech_duration: 0.1
  max_speech_duration: 5.0